language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-31
    - extra-android-m2repository
    - extra-android-support

script:
  - chmod +x ./gradlew
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
